---
engines:
  checks:
    comma-dangle:
      enabled: false
  duplication:
    config:
      languages:
        - ruby
        - javascript
        - python
        - php
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
